# Generated by Django 2.0.7 on 2018-07-21 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artifact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('path', models.CharField(max_length=2000)),
                ('meta', models.CharField(max_length=500, null=True)),
                ('total_comments', models.PositiveIntegerField(default=0, null=True)),
                ('total_mortys', models.PositiveIntegerField(default=0, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Reality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=100)),
                ('total_comments', models.PositiveIntegerField(default=0)),
                ('total_mortys', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='artifact',
            name='reality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='universe.Reality'),
        ),
    ]
